In [1]:
import numpy as np

In [4]:
c = np.array([[11,12], [22,23]])

In [5]:
c


array([[11, 12],
       [22, 23]])

In [6]:
c.shape

(2, 2)

In [7]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [9]:
first = np.arange(12)

In [10]:
first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
second = first.reshape(4,3)

In [13]:
second

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
first[0] = 1000

In [15]:
first

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11])

In [16]:
second

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [17]:
second[0]

array([1000,    1,    2])

In [18]:
second[0][1] = 900

In [19]:
second[0][1]



900

In [20]:
second

array([[1000,  900,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [21]:
second[0]= 800

In [22]:
second

array([[800, 800, 800],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [34]:
second[:][0] = 400

In [28]:
np.zeros((10, 10 ))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.zeros((10, 10), dtype=np.int
        )

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
second

array([[400, 400, 400],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])